### ISSUE TITLE
Correcciones de errores

### ISSUE THREAD

**Issue by eduardofierropro-zz** [raqelcb/rcbdesigner.github.io#1]
Buenas Raquel, 

No sé si se ha subido una versión anterior pero te comento errores de funcinoamiento que veo:
· En las páginas de About, portfolio  y Contact no se carga el CSS.
· Los menús se encuentran vacíos o con el texto (Other)
· En el menú de portfolio cuando intento ir al submenú2 dentro de la flecha, el submenu contenedor desaparece

**Comment by raqelcb** [comment]
Buenas @eduardofierropro 

Estoy arreglándolo al igual que me han desaparecido el grid de imágenes, debe ser algo que toqué en el último momento.
